config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.6
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/orviz/galaxy:
      branch: dev
      repo: https://github.com/orviz/galaxy
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/orviz/galaxy git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-beige-moose.sh
        container: qc.acc_sleazy-corn-caracal
  QC.Doc:
    repos:
      github.com/orviz/galaxy find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.randy-eggplant-giraffe.sh
        container: qc.doc_geeky-puce-shark
      github.com/orviz/galaxy git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-beige-slug.sh
        container: qc.doc_fuzzy-cinnamon-oriole
      github.com/orviz/galaxy markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-xanthic-mongoose.sh
        container: qc.doc_foggy-pink-kiwi
      github.com/orviz/galaxy restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-champagne-raccoon.sh
        container: qc.doc_sleepy-brown-markhor
  QC.Lic:
    repos:
      github.com/orviz/galaxy licensee:
        commands:
        - /usr/bin/env sh .sqa/script.ready-apricot-warthog.sh
        container: qc.lic_dorky-maroon-beagle
  QC.Sec:
    repos:
      github.com/orviz/galaxy bandit:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-razzmatazz-forest.sh
        container: qc.sec_scanty-cream-mayfly
  QC.Sty:
    repos:
      github.com/orviz/galaxy flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-cornflower-newfoundland.sh
        container: qc.sty_flimsy-purple-falcon
      github.com/orviz/galaxy hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-crimson-chipmunk.sh
        container: qc.sty_bumpy-coral-terrier
      github.com/orviz/galaxy jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-heliotrope-hyena.sh
        container: qc.sty_jumpy-corn-binturong
      github.com/orviz/galaxy stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-fuchsia-termite.sh
        container: qc.sty_cloudy-ochre-sponge
  QC.Ver:
    repos:
      github.com/orviz/galaxy get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-seashell-wrasse.sh
        container: qc.ver_baggy-cardinal-vulture
timeout: 5400
