config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/galaxyproject/galaxy:
      branch: release_22.05
      repo: https://github.com/galaxyproject/galaxy
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/galaxyproject/galaxy git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-maroon-macaque.sh
        container: qc.acc_craggy-salmon-harrier
  QC.Doc:
    repos:
      github.com/galaxyproject/galaxy find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-aquamarine-abyssinian.sh
        container: qc.doc_sunny-gold-hummingbird
      github.com/galaxyproject/galaxy git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-aquamarine-chimpanzee.sh
        container: qc.doc_sleazy-teal-quetzal
      github.com/galaxyproject/galaxy markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-denim-fousek.sh
        container: qc.doc_flabby-burgundy-beetle
      github.com/galaxyproject/galaxy restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-taupe-horse.sh
        container: qc.doc_crabby-bronze-civet
  QC.Lic:
    repos:
      github.com/galaxyproject/galaxy licensee:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-smalt-stoat.sh
        container: qc.lic_whiny-cardinal-wasp
  QC.Sec:
    repos:
      github.com/galaxyproject/galaxy bandit:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-aqua-coyote.sh
        container: qc.sec_flimsy-olivine-toucan
  QC.Sty:
    repos:
      github.com/galaxyproject/galaxy flake8:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-lavender-ostrich.sh
        container: qc.sty_snoopy-bronze-caterpillar
      github.com/galaxyproject/galaxy hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-pear-leopard.sh
        container: qc.sty_dorky-seashell-squirt
      github.com/galaxyproject/galaxy jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-rose-hornet.sh
        container: qc.sty_lumpy-peach-dog
      github.com/galaxyproject/galaxy stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-white-zebra.sh
        container: qc.sty_thirsty-alizarin-gar
  QC.Ver:
    repos:
      github.com/galaxyproject/galaxy get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-denim-bullfrog.sh
        container: qc.ver_messy-tangerine-chinook
timeout: 1800
